# "make start-db" (i.e. "docker compose up -d") para arrancar la db 
# "make stop-db" (i.e. "docker compose down") para frenar la db

services:
  postgres:
    image: postgres:17
    container_name: backend-postgres-1
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password 
      POSTGRES_DB: db_back
    ports:
      - "5432:5432"
    volumes:
      - ./src/scripts/db.sql:/docker-entrypoint-initdb.d/db.sql
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
